# ML lab 01 - TensorFlow의 설치 및 기본적인 operations
---

## TensorFlow Hello World!

In [8]:
import tensorflow as tf
import tensorflow as Session

In [12]:
hello = tf.constant("Hello, ,TensorFlow!")
tf.print(hello)

Hello, ,TensorFlow!


## Computational Graph

In [14]:
node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(4.0)
node3 = tf.add(node1, node2)

In [15]:
print("node1:", node1, "node2:", node2)
print("node3: ", node3)

node1: tf.Tensor(3.0, shape=(), dtype=float32) node2: tf.Tensor(4.0, shape=(), dtype=float32)
node3:  tf.Tensor(7.0, shape=(), dtype=float32)


In [18]:
tf.print(node1,node2)
tf.print(node3)

3 4
7


## Placeholder

Session 과 PlaceHolder 는 tensorflow1.0 tensorflow2.0 에서는 @tf.function 을 통해 함수를 정의함으로써 간결하게 처리 가능

In [24]:
import numpy as np

In [28]:
@tf.function
def adder(a, b):
    return a + b
A = tf.constant(1)
B = tf.constant(2)
print(adder(A, B))

C = tf.constant([1, 2])
D = tf.constant([3, 4])
print(adder(C, D))

E = tf.constant([[1, 2, 3], [4, 5, 6]])
F = tf.constant([[2, 3, 4], [5, 6, 7]])
print(adder(E, F))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(
[[ 3  5  7]
 [ 9 11 13]], shape=(2, 3), dtype=int32)


## Everything is Tensor

Rank = 차원
Shapes = []
Types = float32, int32 등등

In [29]:
3
[1., 2., 3.]
[[1., 2., 3.], [4., 5., 6.]]
[[[1., 2., 3.]], [[7., 8., 9.]]]

[[[1.0, 2.0, 3.0]], [[7.0, 8.0, 9.0]]]